substitutions:
  _SERVICE_NAME: user-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:9bd6ac0c1af65bb16002ab9c3b2050828c2c1337774ac5fba7d9fd3b98abed71
    args:
      - generate

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:78f03ad1b806cc4bd173248ae27786a7574c8d166b9cca2b91f68b858008459d
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:78f03ad1b806cc4bd173248ae27786a7574c8d166b9cca2b91f68b858008459d
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:8ea4d1fcd1b24e28dea9f3fbfea84700f60911ca91ce9f3c671d12edf866c0c1
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=FIREBASE_PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
