substitutions:
  _SERVICE_NAME: user-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:d616aaedf90773fc35bf33b1ca5a8f20d1fb497472756803a5ad126912daf0b4
    args:
      - generate

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:721029660d0ccd7c7e542bdd97903ec86e30e0a15c7d6747c7f0a63233ce1746
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:721029660d0ccd7c7e542bdd97903ec86e30e0a15c7d6747c7f0a63233ce1746
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:af6428121e18f3735d27c7ab4c85b58683040ccb3377c83e42e074f4155b9233
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=FIREBASE_PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
