substitutions:
  _SERVICE_NAME: user-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:8dfd08d7d780f66f6b82216455686c8d06b5d954c0f9a0e2a670419d5cae25c1
    args:
      - generate

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:c717f75bf36c9900490da174e86fe447121dd304eaeba2872d1e68811c70c9b9
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:c717f75bf36c9900490da174e86fe447121dd304eaeba2872d1e68811c70c9b9
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:8746f94d215338395b8ba9c0e98cc67fe40c0d524f950c2d6eb74cee95701c68
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=FIREBASE_PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
