substitutions:
  _SERVICE_NAME: user-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:78708a6837209dbe822c75b823521863360fb640501ee5ba95f23c96aa20ca91
    args:
      - generate

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:6d74bb22fe4bc58d209be3f257e18fcf68f855ed426cfb61f2385a4ba73e6b07
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:6d74bb22fe4bc58d209be3f257e18fcf68f855ed426cfb61f2385a4ba73e6b07
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:d59988dd64a6c4da188d5ff55199b6f8bf5131580284fdff70dd99f35b141dcd
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=FIREBASE_PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
