substitutions:
  _SERVICE_NAME: user-service

steps:
  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker@sha256:b2d5cc04d055318de8cc72d2890e7e640a66a010b216844f5cbb68ed36a6c740
    id: build
    args:
      - build
      - -t
      - api-server:latest
      - .
      - --cache-from
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 2: Tag image with COMMIT_SHA
  - name: gcr.io/cloud-builders/docker@sha256:b2d5cc04d055318de8cc72d2890e7e640a66a010b216844f5cbb68ed36a6c740
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image with BRANCH_NAME
  - name: gcr.io/cloud-builders/docker@sha256:b2d5cc04d055318de8cc72d2890e7e640a66a010b216844f5cbb68ed36a6c740
    id: tag-branch
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 4: Tag image as latest
  - name: gcr.io/cloud-builders/docker@sha256:b2d5cc04d055318de8cc72d2890e7e640a66a010b216844f5cbb68ed36a6c740
    id: tag-latest
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 5: Push Docker image
  - name: gcr.io/cloud-builders/docker@sha256:b2d5cc04d055318de8cc72d2890e7e640a66a010b216844f5cbb68ed36a6c740
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 6: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:b63cea81966a2adc85de0b7c31982150ea3b56ca4a0834f15e8d17dcf5745ba4
    id: deploy
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
