substitutions:
  _SERVICE_NAME: user-service

steps:
  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker@sha256:e729082a342559b18a67037884c2a4588e861518f310ba4ecacbc223e8656c6b
    id: build
    args:
      - build
      - -t
      - api-server:latest
      - .
      - --cache-from
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 2: Tag image with COMMIT_SHA
  - name: gcr.io/cloud-builders/docker@sha256:e729082a342559b18a67037884c2a4588e861518f310ba4ecacbc223e8656c6b
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image with BRANCH_NAME
  - name: gcr.io/cloud-builders/docker@sha256:e729082a342559b18a67037884c2a4588e861518f310ba4ecacbc223e8656c6b
    id: tag-branch
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 4: Tag image as latest
  - name: gcr.io/cloud-builders/docker@sha256:e729082a342559b18a67037884c2a4588e861518f310ba4ecacbc223e8656c6b
    id: tag-latest
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 5: Push Docker image
  - name: gcr.io/cloud-builders/docker@sha256:e729082a342559b18a67037884c2a4588e861518f310ba4ecacbc223e8656c6b
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 6: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:a829dd65605970c217e573a9b9f15c004113a35a91b1e210652db943b2a745a0
    id: deploy
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
