substitutions:
  _SERVICE_NAME: user-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:b38ce9a6bad1aee366fd7745c6138c58a72043345ca29e902c18424a52a6647a
    args:
      - generate

  # Step 2: Build a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:0a5bbd5d30b1f19f6bf979fe97bdec5384f7b65cc7e7aaad5a68c78f1d1cba8d
    args:
      - build
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - -t
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
      - .

  # Step 3: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:0a5bbd5d30b1f19f6bf979fe97bdec5384f7b65cc7e7aaad5a68c78f1d1cba8d
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 4: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:caf776ef1626b3cad35668886f67348d8835ab9d820d8df3e95b19d43acdfddf
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=FIREBASE_PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
