// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ride-app/user-service/internal/api-handlers"
	"github.com/ride-app/user-service/internal/repositories/saved-location"
	"github.com/ride-app/user-service/internal/repositories/user"
	"github.com/ride-app/user-service/internal/utils/logger"
	"github.com/ride-app/user-service/third-party"
)

// Injectors from wire.go:

func InitializeService() (*apihandlers.UserServiceServer, error) {
	logrusLogger := logger.New()
	app, err := thirdparty.NewFirebaseApp(logrusLogger)
	if err != nil {
		return nil, err
	}
	firebaseImpl, err := userrepository.NewFirebaseUserRepository(app, logrusLogger)
	if err != nil {
		return nil, err
	}
	savedlocationrepositoryFirebaseImpl, err := savedlocationrepository.NewFirebaseSavedLocationRepository(app, logrusLogger)
	if err != nil {
		return nil, err
	}
	userServiceServer := apihandlers.New(firebaseImpl, savedlocationrepositoryFirebaseImpl, logrusLogger)
	return userServiceServer, nil
}
