// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ride-app/user-service/repositories/saved-location"
	"github.com/ride-app/user-service/repositories/user"
	"github.com/ride-app/user-service/service"
	"github.com/ride-app/user-service/third-party"
)

// Injectors from wire.go:

func InitializeService() (*service.UserServiceServer, error) {
	app, err := thirdparty.NewFirebaseApp()
	if err != nil {
		return nil, err
	}
	firebaseImpl, err := userrepository.NewFirebaseUserRepository(app)
	if err != nil {
		return nil, err
	}
	savedlocationrepositoryFirebaseImpl, err := savedlocationrepository.NewFirebaseSavedLocationRepository(app)
	if err != nil {
		return nil, err
	}
	userServiceServer := service.New(firebaseImpl, savedlocationrepositoryFirebaseImpl)
	return userServiceServer, nil
}
