name: Buf push

on:
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  buf-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - uses: bufbuild/buf-setup-action@f1331ea1d3f74482cbb60ac19f47fa098232b059 # v1.32.0
        with:
          github_token: ${{ github.token }}

      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: api/proto
