name: Merge

on:
  push:
    branches:
      - trunk-merge/**

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    permissions:
      checks: write # For trunk to post annotations
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: go.mod

      - uses: bufbuild/buf-setup-action@aceb106d2419c4cff48863df90161d92decb8591 # v1.35.1
        with:
          buf_user: ${{ env.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}

      - name: Build
        run: docker build .
