name: Merge

permissions: read-all

on:
  push:
    branches:
      - trunk-merge/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    env:
      TEST_TAG: ride/user-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Build and export cache
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
