name: Merge

on:
  push:
    branches:
      - trunk-merge/**

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    permissions:
      checks: write # For trunk to post annotations
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version-file: go.mod

      - uses: bufbuild/buf-setup-action@517ee23296d5caf38df31c21945e6a54bbc8a89f # v1.30.0
        with:
          buf_user: ${{ env.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}

      - name: Build
        run: docker build .
