name: Merge

on:
  push:
    branches:
      - trunk-merge/**

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    permissions:
      checks: write # For trunk to post annotations
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: go.mod

      - uses: bufbuild/buf-setup-action@480a0ee8a588045b52a847b48138c6f377a89519 # v1.31.0
        with:
          buf_user: ${{ env.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}

      - name: Build
        run: docker build .
