name: Nightly

on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:

jobs:
  trunk_check:
    name: Trunk Check Upload
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: buf.build/gen.go
      BUF_USER: debkanchan

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: go.mod

      - uses: bufbuild/buf-setup-action@6bdfab1cc71322c663d891914e69da7a6c2c5f52 # v1.27.1
        with:
          github_token: ${{ github.token }}

      - name: Authenticate buf
        run: echo ${{ secrets.BUF_TOKEN }} | buf registry login --username ${{ env.BUF_USER }} --token-stdin

      - name: Build protobuf
        run: buf generate

      - name: Trunk Check
        uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
