name: Nightly

permissions: read-all

on:
  schedule:
    - cron: 0 0 * * 0-6
  workflow_dispatch:

jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@12da16fcdd5cad1903d0082e591e09df7b67c7f0 # v1
        with:
          prefix: "chore: "
