name: Push

permissions: read-all

on:
  push:
    branches:
      - main

jobs:
  # coverage:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   name: Upload Coverage
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

  #     - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
  #       with:
  #         path: |
  #           ~/.cache/bazel
  #         key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE','MODULE.bazel') }}
  #         restore-keys: |
  #           ${{ runner.os }}-bazel-

  #     - name: Unit Tests
  #       run: bazelisk coverage --combined_report=lcov //...
  #       continue-on-error: true

  #     - run: cp $(bazelisk info output_path)/_coverage/_coverage_report.dat ./

  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@0cfda1dd0a4ad9efc75517f399d859cd1ea4ced1 # v4
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         flags: unit-tests
  #         files: ./_coverage_report.dat
  #         fail_ci_if_error: true
  #         verbose: true

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    env:
      TEST_TAG: ride/user-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Build and export cache
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
